### ISSUE TITLE
Convert Beat tags to cues

### ISSUE THREAD

**Issue by zenibako** [zenibako/q-neiform#1]
As a Beat user, I want the tags I create converted into cues so I can review and upload them to QLab.

The format should be something like this:
```yaml
name: Lorem Ipsum
notes: Veniam reprehenderit in proident labore fugiat laboris.
cues:
  - name: NARRATOR: Velit do est mollit qui a...
    notes: Sed occaecat fugiat est aute ipsum.
    id: 0dbc3ee8-4387-4d29-9998-e8659a94e0f5
    range: [9, 25]
  - name: NARRATOR: ...culpa exercitation laboru.
    notes: Magna commodo in, eiusmod aliquip sit laboris.
    id: c4e67e52-ceda-4361-acee-03791a94ea41
    range: [34, 25]
```
